import { validateContentSafety, validateResponseBounds } from '../guardrails/validators.js';

/**
 * Guardrail Test 6: Verify no harmful content in responses
 * Ensures LLM-generated content stays within safety bounds
 */
export const testGuardrailNoHarmfulContent = async (page) => {
  // Simulate an LLM response (in real scenario, this would be generated by AI)
  const aiGeneratedText = 'Create a new helpful task for your day';

  const validation = validateContentSafety(aiGeneratedText);

  if (!validation.safe) {
    throw new Error(
      `Harmful keywords detected: ${validation.foundKeywords.join(', ')}`
    );
  }

  return {
    passed: true,
    text: aiGeneratedText,
    validation,
  };
};

/**
 * Guardrail Test 7: Verify response bounds (token limit, format)
 * Ensures responses are within acceptable performance/safety bounds
 */
export const testGuardrailResponseBounds = async (page, API) => {
  const startTime = Date.now();

  try {
    const response = await API.get('/tasks');
    const endTime = Date.now();

    const bounds = validateResponseBounds({
      time: endTime - startTime,
      data: response.data,
      status: response.status,
    });

    // Guardrail: Response time < 5 seconds
    if (bounds.responseTime > 5000) {
      throw new Error(`Response time exceeded: ${bounds.responseTime}ms > 5000ms`);
    }

    // Guardrail: Must have valid JSON
    if (!bounds.hasData) {
      throw new Error('Response has no data');
    }

    return {
      passed: true,
      responseTime: bounds.responseTime,
      bounds,
    };
  } catch (err) {
    throw new Error(`Response bounds violation: ${err.message}`);
  }
};
